### ISSUE TITLE
跑不通例程Realsense_Get_Picture.py

### ISSUE THREAD

**Issue by OriginalReimu** [DonovanZhu/Unitree_RoBoCom#1]
```
import cv
import pyrealsense2
```
成功
运行ls /dev/video* 识别到3个摄像头
但是执行Realsense_Get_Picture.py时报错：
```
Traceback (most recent call last):
  File "Realsense_Get_Picture.py", line 11, in <module>
    pipeline_profile = config.resolve(pipeline_wrapper)
RuntimeError: No device connected
```

Raspberry Pi 4B
Python 3.7.3
numpy 1.16.2
Unitree A1
![运行截图](https://i.loli.net/2021/09/27/QmV3aRS5OAXY8t1.png)

**Comment by DonovanZhu** [comment]
1. 确认是按照readme安装pyrealsense2软件包
2. 在终端中输入realsense-viewer，确认是否可以检查到摄像头
3.  重新插拔摄像头，再次尝试

**Comment by OriginalReimu** [comment]
1.确实是按照readme安装的，与README不同的是执第50行`source ~/.bashrc`时报错`bash: export: “/usr/lib/python3/dist-packages/pyrealsense2”: 不是有效的标识符`，将47行`export PYTHONPATH=$PYTHONPATH: /usr/lib/python3/dist-packages/pyrealsense2`修改为`export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages/pyrealsense2`(删除了/usr前的空格)才成功执行`source ~/.bashrc`![Pic1.png](https://i.loli.net/2021/09/27/bHd6AmeW8ugD7QE.png)

2.realsense-viewer也无法检查到摄像头![realsense-viewer](https://i.loli.net/2021/09/27/h3PiAOWUyqae5L4.png)

3.狗和树莓派都重启过，还是不行

**Comment by DonovanZhu** [comment]
这个是直接在A1上安装的吗，A1的树莓派本身有一个自启动程序，是和摄像头相关的，这个有关闭吗？如果没有的话可以在终端输入htop看看有没有和robot_vision相关的程序在运行，可能是该程序占用了摄像头

**Comment by OriginalReimu** [comment]
是指RobotVisionSystem吗，那个已经kill掉了，但还是不行。

**Comment by DonovanZhu** [comment]
按照我之前的测试这个安装是可以在pi上跑通的。我去找个A1再测试一下吧

**Comment by DonovanZhu** [comment]
我更新了安装步骤，将build文件夹清空后从cmake那步开始安装。目前新方法在我的A1上可以正确安装了。

**Comment by OriginalReimu** [comment]
可以了，非常感谢！
