### ISSUE TITLE
x86与控制器通信

### ISSUE THREAD

**Issue by OriginalReimu** [DonovanZhu/Unitree_RoBoCom#2]
抱歉，又遇到问题了，麻烦你了。
在x86上编译Color_Detection.cpp后得到的./Color_Detection可以收到树莓派的指令，但机器狗并没有动。
图中为./Color_Detection运行界面
![upboard.jpg](https://i.loli.net/2021/09/28/nNiYhavA1cHKZmu.jpg)

**Comment by DonovanZhu** [comment]
可能是机器狗上面的运动程序没有更新，售后那边有给你发x86上最新的运动程序吗？就是x86里Unitree文件夹内的程序。

**Comment by xxd-xy** [comment]
请问一下，这个是什么问题呢
![4D0083A9D081623690F88E906E09F4B3](https://user-images.githubusercontent.com/58600456/135709092-c1ac7a96-f969-4cea-8158-2f44c418eb09.jpg)

**Comment by xxd-xy** [comment]
> 抱歉，又遇到问题了，麻烦你了。 在x86上编译Color_Detection.cpp后得到的./Color_Detection可以收到树莓派的指令，但机器狗并没有动。 图中为./Color_Detection运行界面 ![upboard.jpg](https://camo.githubusercontent.com/ad432acefa533a9354e5a239f23163c04c22a6da8943b737b12f15b1de6bcf3b/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30392f32382f6e4e6959686176413163484b5a6d752e6a7067)

你好，这个demo你成功了吗

**Comment by OriginalReimu** [comment]
已经可以了，需要找客服要最新的unitree固件。

**Comment by xxd-xy** [comment]
> 已经可以了，需要找客服要最新的unitree固件。

好的好的  我们也是一样 更新了一下运动程序

**Comment by OriginalReimu** [comment]
是
